"""empty message

Revision ID: a2cfeed6f4c6
Revises: 673160eac2a0
Create Date: 2018-12-09 12:31:31.120560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2cfeed6f4c6'
down_revision = '673160eac2a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('publish', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'publish')
    # ### end Alembic commands ###
